version: "3.8"
services:
  backend:
    image: "aboubacar/springboot-react-fullstack:13.4.2023.14.12.32"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev