version: "3.8"
services:
  backend:
    image: "aboubacar/springboot-react-fullstack:11.4.2023.13.10.36"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev